apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  tekton:
    steps:
    - name: hello
      uses: docker://alpine:3
      shell: sh
      run: |
        echo "Hello, world! I'm $(whoami) on $(hostname)"
  edge:
    with:
      script: |
        echo "Hello world! I'm $(whoami) on $(hostname)"
      labels: "hari-macos-arm64"
    delegates: https://github.com/EgdeRunnerTest/EdgeRunnerTest/custom-job.yml