apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: uc2-conditional-label
on:
  workflow_dispatch:
    inputs:
      use_gpu:
        type: boolean
        default: false

jobs:
  ml-training:
    runs-on:
      - ${{ vars.BASE_RUNNER }}
      - ${{ inputs.use_gpu && vars.GPU_LABEL || '' }}
    steps:
      - name: Say hello
        shell: sh
        run: |
          echo "hello world"
